### ISSUE TITLE
Sympy online shell seems never finishing loading or initializing.

### ISSUE THREAD

**Issue by markgao11** [sympy/live#21]
I tried to use the online shell
@ https://www.sympy.org/en/shell.html

but the loading process seems  never finishing.

always displaying [*]:

[*]:  from sympy import *
 from sympy import *
 init_printing()
 x, y, z, t = symbols('x y z t')
 k, m, n = symbols('k m n', integer=True)
 f, g, h = symbols('f g h', cls=Function)
...

Thanks for your attention.
Mark

**Comment by asmeurer** [comment]
I see this too. I get the following error in the console

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 365, in run_async
    await coroutine
  File "<exec>", line 6, in <module>
  File "/lib/python3.11/site-packages/pyodide_kernel/__init__.py", line 20, in <module>
    from .display import LiteStream
  File "/lib/python3.11/site-packages/pyodide_kernel/display.py", line 4, in <module>
    from IPython.core.displayhook import DisplayHook
  File "/lib/python3.11/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/lib/python3.11/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py", line 48, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/lib/python3.11/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/lib/python3.11/site-packages/IPython/core/completer.py", line 219, in <module>
    from IPython.core.guarded_eval import guarded_eval, EvaluationContext
  File "/lib/python3.11/site-packages/IPython/core/guarded_eval.py", line 40, in <module>
    from typing_extensions import TypeAliasType
ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/lib/python3.11/site-packages/typing_extensions.py)

    at new_error (pyodide.asm.js:9:14992)
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at _PyCFunctionWithKeywords_TrampolineCall (pyodide.asm.js:9:126959)
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at Module.callPyObjectKwargs (pyodide.asm.js:9:75551)
    at Module.callPyObject (pyodide.asm.js:9:75996)
    at wrapper (pyodide.asm.js:9:57850)
```

**Comment by JZimmerman12** [comment]
It seems to be working again.  I've been able to run code on it for the past few minutes.

**Comment by agriyakhetarpal** [comment]
SymPy Live has been working again and Pyodide has had a few releases by now. Considering that there have not been any similar issues recently, we should be in a position to close this. Please feel free to reopen it if you face another problem. Thank you!
